Box values before storing them in AtomicPtr
soenkehahn/rust-skipchannel pull request #2
Opened 2018-08-19 16:55 UTC by jondistad

2018-08-21 15:09 UTC, soenkehahn commented
I think I want to release this to crates.io. So it'd be nice if this worked with rust stable.

Also, can you point this PR at `master`, please?

2018-08-21 15:10 UTC, soenkehahn requested changes
Wrote a comment with some requests for changes. Will review again after those are addressed.

2018-08-21 23:26 UTC, jondistad commented
@soenkehahn ready for another review

2018-09-01 19:19 UTC, soenkehahn requested changes

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +//! assert_eq!(thread.join().unwrap(), Box::new(Some(1)));
As I understand you do this to avoid having to copy the value from the heap into the stack of the calling function. Is that right? If yes, I'd like to keep this change out of this PR. I think this PR should focus on switching to atomic references. Just to keep discussions focused.

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +            Box::from_raw(old); // Re-box the pointer so it gets properly dropped
Can we have a test for this behavior instead of a comment?

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +            .swap(Box::into_raw(Box::new(None)), Ordering::Relaxed);
Can we use `Ordering::SeqCst`? I don't fully understand these orderings yet, but that seems like the safe choice.

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +            let old = self.ptr.swap(Box::into_raw(Box::new(Some(t))), Ordering::Relaxed);
This line is not `unsafe`.

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +        let r = self
Can we use a more telling name than `r`?

2018-09-01 19:19 UTC, soenkehahn commented on src/lib.rs
> +            assert_eq!(thread.join().unwrap(), Box::new(Some(1)));
I think we should avoid copying the doctest here. It's just likely to get out of sync...

2018-09-01 19:37 UTC, soenkehahn commented on src/lib.rs
> +//! assert_eq!(thread.join().unwrap(), Box::new(Some(1)));
Done.

2018-09-01 19:44 UTC, soenkehahn commented on src/lib.rs
> +            let old = self.ptr.swap(Box::into_raw(Box::new(Some(t))), Ordering::Relaxed);
Done.

2018-09-01 21:21 UTC, soenkehahn commented on src/lib.rs
> +            Box::from_raw(old); // Re-box the pointer so it gets properly dropped
Done.

2018-09-01 21:33 UTC, soenkehahn commented on src/lib.rs
> +            .swap(Box::into_raw(Box::new(None)), Ordering::Relaxed);
Done.

2018-09-01 21:34 UTC, soenkehahn commented on src/lib.rs
> +        let r = self
Done.

2018-09-01 21:38 UTC, soenkehahn commented on src/lib.rs
> +            assert_eq!(thread.join().unwrap(), Box::new(Some(1)));
Done.

2018-09-01 21:38 UTC, soenkehahn approved these changes

2018-09-02 14:17 UTC, catharinejm commented
Good catch, dropping the last unread value inside the `AtomicPtr`

I'm a-mergin'

2018-09-02 14:17 UTC, merged